# 라이브러리 불러오기

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

# 데이터 불러오기

In [2]:
train = pd.read_csv("/data/round1_train.csv")

In [42]:
train

시각                                               ADID  \
0        20220403000000  45503fc5d8d3a06832a087581ff6b6b4937b4d41d2d2cd...   
1        20220403000000  59ae8bfa45031b28d30dc1ad6486d702148b1fbd461fd5...   
2        20220403000000  c57351c77526224145cc7a5f48de890754943c71363d80...   
3        20220403000000  93aca0b9a68e60ff423feeeae48d02007fab3920bc5d4f...   
4        20220403000000  92a710e711b4d911c9c20ce04c6ce0381a3fbd9dcb3ba3...   
...                 ...                                                ...   
8525507  20220409235959  c3f09ead5c48d3963994bb1d22ee3e5aabc6231962ba1d...   
8525508  20220409235959  14e0b00bb97e4aaa523e034f7a3ab7c960f60776d29766...   
8525509  20220409235959  563c88c3eb3e455273f843430be728dbce40666ba15f66...   
8525510  20220409235959  7780f913123f259c2ec2a48770a23fb5e97791fecaa76b...   
8525511  20220409235959  aeb260a9bbd44de63bb727ef5e7a2775934e92ecca9c15...   

         ADID 타입                                             DSP ID  \
0              1  d22127d7ef82d6f222558447b65f1fb63c36a55d71d0c3...   
1              1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
2              5  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
3              1  d22127d7ef82d6f222558447b65f1fb63c36a55d71d0c3...   
4              1  d22127d7ef82d6f222558447b65f1fb63c36a55d71d0c3...   
...          ...                                                ...   
8525507        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525508        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525509        5  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525510        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525511        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   

                                                     매체 ID  \
0        03eef1b13012d013345f17def773eceda258d8d9829484...   
1        d64dbe2039165cce22fae7c7f16259596a196f149f08e7...   
2        75cb5f369879cd6fa900bea129c1037432a00d6ae94128...   
3        03eef1b13012d013345f17def773eceda258d8d9829484...   
4        03eef1b13012d013345f17def773eceda258d8d9829484...   
...                                                    ...   
8525507  d64dbe2039165cce22fae7c7f16259596a196f149f08e7...   
8525508  554b9474090ae6e25f9c6b93294eb85a2ef720ee49476d...   
8525509  58e82266d3dd5e06208ea5e5935130faf276e4f95c3553...   
8525510  554b9474090ae6e25f9c6b93294eb85a2ef720ee49476d...   
8525511  554b9474090ae6e25f9c6b93294eb85a2ef720ee49476d...   

                                                   애드유닛 ID  플랫폼  OS 종류  \
0        4a3406328504b21257aa66fc138ba78668bef318b361f9...    1      1   
1        a2f05b9f2662f44757f69656801c4c0bd83e95caa10ddb...    1      1   
2        40f3cb27c781d1130b7565836803f952a2e327e6db72ae...    3      1   
3        4a3406328504b21257aa66fc138ba78668bef318b361f9...    1      1   
4        4a3406328504b21257aa66fc138ba78668bef318b361f9...    1      1   
...                                                    ...  ...    ...   
8525507  a2f05b9f2662f44757f69656801c4c0bd83e95caa10ddb...    1      1   
8525508  dc83186485f48c299c25f841bc8b866f4b80d901d825fe...    1      1   
8525509  95380be2c6bdb9fddef405417310251a1f3524b3761033...    3      1   
8525510  dc83186485f48c299c25f841bc8b866f4b80d901d825fe...    1      1   
8525511  dc83186485f48c299c25f841bc8b866f4b80d901d825fe...    1      1   

         사이즈 ID                                              노출 ID  ...  \
0             3  eb2cb8788b9462b49c35c1ca9a4b5828b9153274041a3a...  ...   
1             2  c215404374628df7ea645a3cbc8a40df8972ca95b46f30...  ...   
2             3  ed2e5996d4f0f524177eb84050fb10680899d93dc8d1fe...  ...   
3             3  71d399d29493273a7b33fd13344c6ba7764b5e336df44a...  ...   
4             3  003d0bfc2d6181540c0343eb1b5b242b7219c1878d581e...  ...   
...         ...                                                ...  ...   
8525507       2  78166d8ab99d327af1ae07155115cc4ea85281ecdc5b90...  ... 

## Feature Engineering

In [3]:
# P1 ~ P4를 사용해 P5를 예측
temp = train.loc[:,['P1','P2','P3','P4','P5']]
new_temp = temp.loc[temp['P5'] != 0, :]

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
model = LinearRegression()
x = new_temp.drop(columns='P5')
y = new_temp.loc[:, 'P5']
x_train_temp, x_test_temp, y_train_temp, y_test_temp = train_test_split(x, y, test_size=0.1, random_state=2022)

# P5를 예측하는 Linear Regression 모델 학습
model.fit(x_train_temp, y_train_temp)

LinearRegression()

In [31]:
# 모델 저장
from joblib import dump, load
dump(model, 'model_lr.joblib') 

['model_lr.joblib']

In [32]:
load_model_lr = load('/result/model_lr.joblib') 

In [33]:
new_feat = load_model_lr.predict(train[['P1','P2','P3','P4']])
new_feat

array([ 40.23323022, 603.81662291, 268.15733423, ..., 365.36063923,
        78.53389865,  78.53389865])

In [8]:
# 새로운 feature 1 행 추가
train['new_feature'] = new_feat

In [10]:
# 새로운 feature 2 행 추가
train['new_feature2'] = 0
train.loc[(train['P2'] > train['P4']) | (train['P3'] > train['P4']), 'new_feature2'] = 0
train.loc[(train['P2'] < train['P4']) & (train['P3'] < train['P4']), 'new_feature2'] = 1

In [11]:
# 새로운 feature 3, 4 행 추가
train['P4_P3'] = train['P4'] - train['P3']
train['P4_P2'] = train['P4'] - train['P2']

In [12]:
train

시각                                               ADID  \
0        20220403000000  45503fc5d8d3a06832a087581ff6b6b4937b4d41d2d2cd...   
1        20220403000000  59ae8bfa45031b28d30dc1ad6486d702148b1fbd461fd5...   
2        20220403000000  c57351c77526224145cc7a5f48de890754943c71363d80...   
3        20220403000000  93aca0b9a68e60ff423feeeae48d02007fab3920bc5d4f...   
4        20220403000000  92a710e711b4d911c9c20ce04c6ce0381a3fbd9dcb3ba3...   
...                 ...                                                ...   
8525507  20220409235959  c3f09ead5c48d3963994bb1d22ee3e5aabc6231962ba1d...   
8525508  20220409235959  14e0b00bb97e4aaa523e034f7a3ab7c960f60776d29766...   
8525509  20220409235959  563c88c3eb3e455273f843430be728dbce40666ba15f66...   
8525510  20220409235959  7780f913123f259c2ec2a48770a23fb5e97791fecaa76b...   
8525511  20220409235959  aeb260a9bbd44de63bb727ef5e7a2775934e92ecca9c15...   

         ADID 타입                                             DSP ID  \
0              1  d22127d7ef82d6f222558447b65f1fb63c36a55d71d0c3...   
1              1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
2              5  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
3              1  d22127d7ef82d6f222558447b65f1fb63c36a55d71d0c3...   
4              1  d22127d7ef82d6f222558447b65f1fb63c36a55d71d0c3...   
...          ...                                                ...   
8525507        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525508        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525509        5  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525510        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   
8525511        1  becd0e5686fae9c4a1885a950817a70f9ae3c437d32a60...   

                                                     매체 ID  \
0        03eef1b13012d013345f17def773eceda258d8d9829484...   
1        d64dbe2039165cce22fae7c7f16259596a196f149f08e7...   
2        75cb5f369879cd6fa900bea129c1037432a00d6ae94128...   
3        03eef1b13012d013345f17def773eceda258d8d9829484...   
4        03eef1b13012d013345f17def773eceda258d8d9829484...   
...                                                    ...   
8525507  d64dbe2039165cce22fae7c7f16259596a196f149f08e7...   
8525508  554b9474090ae6e25f9c6b93294eb85a2ef720ee49476d...   
8525509  58e82266d3dd5e06208ea5e5935130faf276e4f95c3553...   
8525510  554b9474090ae6e25f9c6b93294eb85a2ef720ee49476d...   
8525511  554b9474090ae6e25f9c6b93294eb85a2ef720ee49476d...   

                                                   애드유닛 ID  플랫폼  OS 종류  \
0        4a3406328504b21257aa66fc138ba78668bef318b361f9...    1      1   
1        a2f05b9f2662f44757f69656801c4c0bd83e95caa10ddb...    1      1   
2        40f3cb27c781d1130b7565836803f952a2e327e6db72ae...    3      1   
3        4a3406328504b21257aa66fc138ba78668bef318b361f9...    1      1   
4        4a3406328504b21257aa66fc138ba78668bef318b361f9...    1      1   
...                                                    ...  ...    ...   
8525507  a2f05b9f2662f44757f69656801c4c0bd83e95caa10ddb...    1      1   
8525508  dc83186485f48c299c25f841bc8b866f4b80d901d825fe...    1      1   
8525509  95380be2c6bdb9fddef405417310251a1f3524b3761033...    3      1   
8525510  dc83186485f48c299c25f841bc8b866f4b80d901d825fe...    1      1   
8525511  dc83186485f48c299c25f841bc8b866f4b80d901d825fe...    1      1   

         사이즈 ID                                              노출 ID  ...  \
0             3  eb2cb8788b9462b49c35c1ca9a4b5828b9153274041a3a...  ...   
1             2  c215404374628df7ea645a3cbc8a40df8972ca95b46f30...  ...   
2             3  ed2e5996d4f0f524177eb84050fb10680899d93dc8d1fe...  ...   
3             3  71d399d29493273a7b33fd13344c6ba7764b5e336df44a...  ...   
4             3  003d0bfc2d6181540c0343eb1b5b242b7219c1878d581e...  ...   
...         ...                                                ...  ...   
8525507       2  78166d8ab99d327af1ae07155115cc4ea85281ecdc5b90...  ... 

## 데이터 전처리

In [13]:
# ID관련 column, 시각, P5, 광고 응답 소재 카테고리 행 삭제
train.drop(columns=['시각', 'ADID', 'DSP ID', '매체 ID', '애드유닛 ID', '노출 ID', 'SSP 입찰ID', 'DSP 입찰ID', 'AX 낙찰ID', 'WUID (웹 유저 ID)', 'OS 버전 ID', '국가코드 ID', 'P5', '광고 응답 소재 카테고리'], inplace=True)

In [14]:
# 결측치 확인
train.isna().sum()

ADID 타입             0
플랫폼                 0
OS 종류               0
사이즈 ID              0
환율                  0
광고 응답 광고주 도메인    3012
P1                  0
P2                  0
P3                  0
P4                  0
winning             0
new_feature         0
new_feature2        0
P4_P3               0
P4_P2               0
dtype: int64

In [15]:
# 결측치 행 제거
train.dropna(inplace=True)

In [16]:
# 데이터 결측치 확인
train.isna().sum()

ADID 타입          0
플랫폼              0
OS 종류            0
사이즈 ID           0
환율               0
광고 응답 광고주 도메인    0
P1               0
P2               0
P3               0
P4               0
winning          0
new_feature      0
new_feature2     0
P4_P3            0
P4_P2            0
dtype: int64

In [17]:
# 가변수화할 행의 범주 개수 파악하기.
len(train['ADID 타입'].unique()),len(train['플랫폼'].unique()),len(train['OS 종류'].unique()),len(train['사이즈 ID'].unique()),len(train['광고 응답 광고주 도메인'].unique())

(4, 3, 2, 3, 2473)

In [18]:
# 광고 응답 광고주 도메인이 너무 많은 범주를 가지므로 제거
train.drop(columns=['광고 응답 광고주 도메인'], inplace=True)

In [19]:
# 가변수화
train_d = pd.get_dummies(train, columns=['ADID 타입', '플랫폼', 'OS 종류', '사이즈 ID'], drop_first=True)

In [20]:
# 행 이름 확인
list(train_d)

['환율',
 'P1',
 'P2',
 'P3',
 'P4',
 'winning',
 'new_feature',
 'new_feature2',
 'P4_P3',
 'P4_P2',
 'ADID 타입_2',
 'ADID 타입_5',
 'ADID 타입_7',
 '플랫폼_2',
 '플랫폼_3',
 'OS 종류_2',
 '사이즈 ID_2',
 '사이즈 ID_3']

In [21]:
# 데이터에서 x, y 분리
x = train_d.drop(columns=['winning'])
y = train_d.loc[:, 'winning']

In [22]:
x.shape, y.shape

((8522500, 17), (8522500,))

In [23]:
# train set, validation set split
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.1, random_state=2022)

# 데이터 양이 많으므로 test_size는 0.1의 비율로 설정

In [24]:
x_train.shape, x_val.shape, y_train.shape, y_val.shape

((7670250, 17), (852250, 17), (7670250,), (852250,))

## 모델링 시작

### GPU 환경인지 확인

In [27]:
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


## Random Forest 모델

In [67]:
# sklearn에서 모델 불러오기
from sklearn.ensemble import RandomForestClassifier

In [68]:
# 모델 선언과 학습
model_rf = RandomForestClassifier()
model_rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [70]:
# 모델 예측 및 결과
from sklearn.metrics import *
pred_rf = model_rf.predict(x_val)

print(confusion_matrix(y_val, pred_rf))
print(classification_report(y_val, pred_rf))

[[560333  40963]
 [ 79924 171030]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90    601296
           1       0.81      0.68      0.74    250954

    accuracy                           0.86    852250
   macro avg       0.84      0.81      0.82    852250
weighted avg       0.86      0.86      0.85    852250



### 모델 저장

In [36]:
# 모델 저장
from joblib import dump, load
dump(model_rf, 'model_rf.joblib') 

['model_rf.joblib']

In [37]:
from joblib import dump, load
load_model_rf = load('/result/model_rf.joblib') 
pred_rf = load_model_rf.predict(x_val)
print(confusion_matrix(y_val, pred_rf))
print(classification_report(y_val, pred_rf))

[[560333  40963]
 [ 79924 171030]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90    601296
           1       0.81      0.68      0.74    250954

    accuracy                           0.86    852250
   macro avg       0.84      0.81      0.82    852250
weighted avg       0.86      0.86      0.85    852250

